### model
model_name_or_path: /home/lizijian/Models/Llama-2-7b-chat-hf
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
# lora_dropout: 0.0
lora_target: q_proj, v_proj

### dataset
dataset: gsm8k
template: llama2_gsm8k
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/llama2-7b-chat-lora-sft-gsm8k
logging_steps: 10
save_steps: 10
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: llama2-7b-chat-lora-sft-gsm8k

### train
per_device_train_batch_size: 32
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 6.0
lr_scheduler_type: linear
# warmup_ratio: 0.01
warmup_steps: 64
# weight_decay: 0.0
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
